DELETE FROM "Country";
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(1, 'AD', 'Andorra', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(2, 'AE', 'U.A.E.', 'الإمارات العربية المتحدة');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(3, 'AF', 'Afghanistan', 'افغانستان');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(4, 'AG', 'Antigua and Barbuda', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(5, 'AI', 'Anguilla', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(6, 'AL', 'Albania', 'Shqipëria');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(7, 'AM', 'Armenia', 'Հայաստան');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(8, 'AO', 'Angola', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(9, 'AQ', 'Antarctica', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(10, 'AR', 'Argentina', 'Argentina');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(11, 'AS', 'American Samoa', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(12, 'AT', 'Austria', 'Österreich');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(13, 'AU', 'Australia', 'Australia');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(14, 'AW', 'Aruba', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(15, 'AX', 'Ĺland Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(16, 'AZ', 'Azerbaijan', 'Азәрбајҹан');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(17, 'BA', 'Bosnia and Herzegovina', 'Bosna i Hercegovina');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(18, 'BB', 'Barbados', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(19, 'BD', 'Bangladesh', 'বাংলাদেশ');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(20, 'BE', 'Belgium', 'België');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(21, 'BF', 'Burkina Faso', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(22, 'BG', 'Bulgaria', 'България');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(23, 'BH', 'Bahrain', 'البحرين');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(24, 'BI', 'Burundi', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(25, 'BJ', 'Benin', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(26, 'BL', 'Saint Barthélemy', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(27, 'BM', 'Bermuda', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(28, 'BN', 'Brunei Darussalam', 'Brunei Darussalam');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(29, 'BO', 'Bolivia', 'Bolivia');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(30, 'BQ', 'Caribbean Netherlands ', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(31, 'BR', 'Brazil', 'Brasil');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(32, 'BS', 'Bahamas', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(33, 'BT', 'Bhutan', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(34, 'BV', 'Bouvet Island', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(35, 'BW', 'Botswana', 'Botswana');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(36, 'BY', 'Belarus', 'Беларусь');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(37, 'BZ', 'Belize', 'Belize');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(38, 'CA', 'Canada', 'Canada');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(39, 'CC', 'Cocos (Keeling) Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(40, 'CD', 'Congo', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(41, 'CF', 'Central African Republic', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(42, 'CG', 'Congo', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(43, 'CH', 'Switzerland', 'Svizzera');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(44, 'CI', 'Côte d''Ivoire', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(45, 'CK', 'Cook Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(46, 'CL', 'Chile', 'Chile');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(47, 'CM', 'Cameroon', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(48, 'CN', 'China', '中华人民共和国');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(49, 'CO', 'Colombia', 'Colombia');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(50, 'CR', 'Costa Rica', 'Costa Rica');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(51, 'CU', 'Cuba', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(52, 'CV', 'Cape Verde', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(53, 'CW', 'Curaçao', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(54, 'CX', 'Christmas Island', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(55, 'CY', 'Cyprus', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(56, 'CZ', 'Czech Republic', 'Česká republika');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(57, 'DE', 'Germany', 'Deutschland');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(58, 'DJ', 'Djibouti', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(59, 'DK', 'Denmark', 'Danmark');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(60, 'DM', 'Dominica', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(61, 'DO', 'Dominican Republic', 'República Dominicana');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(62, 'DZ', 'Algeria', 'الجزائر');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(63, 'EC', 'Ecuador', 'Ecuador');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(64, 'EE', 'Estonia', 'Eesti');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(65, 'EG', 'Egypt', 'مصر');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(66, 'EH', 'Western Sahara', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(67, 'ER', 'Eritrea', 'ኤርትራ');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(68, 'ES', 'Spain', 'España');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(69, 'ET', 'Ethiopia', 'ኢትዮጵያ');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(70, 'FI', 'Finland', 'Suomi');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(71, 'FJ', 'Fiji', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(72, 'FK', 'Falkland Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(73, 'FM', 'Micronesia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(74, 'FO', 'Faroe Islands', 'Føroyar');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(75, 'FR', 'France', 'France');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(76, 'GA', 'Gabon', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(77, 'GB', 'United Kingdom', 'United Kingdom');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(78, 'GD', 'Grenada', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(79, 'GE', 'Georgia', 'საქართველო');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(80, 'GF', 'French Guiana', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(81, 'GG', 'Guernsey', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(82, 'GH', 'Ghana', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(83, 'GI', 'Gibraltar', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(84, 'GL', 'Greenland', 'Kalaallit Nunaat');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(85, 'GM', 'Gambia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(86, 'GN', 'Guinea', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(87, 'GP', 'Guadeloupe', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(88, 'GQ', 'Equatorial Guinea', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(89, 'GR', 'Greece', 'Ελλάδα');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(90, 'GS', 'South Georgia and the South Sandwich Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(91, 'GT', 'Guatemala', 'Guatemala');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(92, 'GU', 'Guam', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(93, 'GW', 'Guinea-Bissau', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(94, 'GY', 'Guyana', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(95, 'HK', 'Hong Kong SAR', '香港特別行政區');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(96, 'HM', 'Heard and McDonald Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(97, 'HN', 'Honduras', 'Honduras');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(98, 'HR', 'Croatia', 'Hrvatska');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(99, 'HT', 'Haiti', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(100, 'HU', 'Hungary', 'Magyarország');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(101, 'ID', 'Indonesia', 'Indonesia');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(102, 'IE', 'Ireland', 'Ireland');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(103, 'IL', 'Israel', 'ישראל');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(104, 'IM', 'Isle of Man', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(105, 'IN', 'India', 'भारत');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(106, 'IO', 'British Indian Ocean Territory', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(107, 'IQ', 'Iraq', 'العراق');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(108, 'IR', 'Iran', 'ایران');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(109, 'IS', 'Iceland', 'Ísland');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(110, 'IT', 'Italy', 'Italia');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(111, 'JE', 'Jersey', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(112, 'JM', 'Jamaica', 'Jamaica');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(113, 'JO', 'Jordan', 'الأردن');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(114, 'JP', 'Japan', '日本');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(115, 'KE', 'Kenya', 'Kenya');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(116, 'KG', 'Kyrgyzstan', 'Кыргызстан');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(117, 'KH', 'Cambodia', 'កម្ពុជា');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(118, 'KI', 'Kiribati', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(119, 'KM', 'Comoros', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(120, 'KN', 'Saint Kitts and Nevis', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(121, 'KP', 'North Korea', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(122, 'KR', 'Korea', '대한민국');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(123, 'KW', 'Kuwait', 'الكويت');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(124, 'KY', 'Cayman Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(125, 'KZ', 'Kazakhstan', 'Қазақстан');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(126, 'LA', 'Lao PDR', 'ສປປ ລາວ');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(127, 'LB', 'Lebanon', 'لبنان');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(128, 'LC', 'Saint Lucia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(129, 'LI', 'Liechtenstein', 'Liechtenstein');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(130, 'LK', 'Sri Lanka', 'ශ්‍රී ලංකා');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(131, 'LR', 'Liberia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(132, 'LS', 'Lesotho', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(133, 'LT', 'Lithuania', 'Lietuva');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(134, 'LU', 'Luxembourg', 'Lëtzebuerg');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(135, 'LV', 'Latvia', 'Latvija');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(136, 'LY', 'Libya', 'ليبيا');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(137, 'MA', 'Morocco', 'المملكة المغربية');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(138, 'MC', 'Principality of Monaco', 'Principauté de Monaco');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(139, 'MD', 'Moldova', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(140, 'ME', 'Montenegro', 'Crna Gora');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(141, 'MF', 'Saint-Martin (France)', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(142, 'MG', 'Madagascar', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(143, 'MH', 'Marshall Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(144, 'MK', 'Macedonia (Former Yugoslav Republic of Macedonia)', 'Македонија');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(145, 'ML', 'Mali', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(146, 'MM', 'Myanmar', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(147, 'MN', 'Mongolia', 'Монгол улс');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(148, 'MO', 'Macao SAR', '澳門特別行政區');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(149, 'MP', 'Northern Mariana Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(150, 'MQ', 'Martinique', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(151, 'MR', 'Mauritania', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(152, 'MS', 'Montserrat', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(153, 'MT', 'Malta', 'Malta');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(154, 'MU', 'Mauritius', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(155, 'MV', 'Maldives', 'ދިވެހި ރާއްޖެ');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(156, 'MW', 'Malawi', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(157, 'MX', 'Mexico', 'México');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(158, 'MY', 'Malaysia', 'Malaysia');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(159, 'MZ', 'Mozambique', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(160, 'NA', 'Namibia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(161, 'NC', 'New Caledonia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(162, 'NE', 'Niger', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(163, 'NF', 'Norfolk Island', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(164, 'NG', 'Nigeria', 'Nigeria');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(165, 'NI', 'Nicaragua', 'Nicaragua');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(166, 'NL', 'Netherlands', 'Nederland');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(167, 'NO', 'Norway', 'Noreg');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(168, 'NP', 'Nepal', 'नेपाल');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(169, 'NR', 'Nauru', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(170, 'NU', 'Niue', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(171, 'NZ', 'New Zealand', 'New Zealand');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(172, 'OM', 'Oman', 'عمان');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(173, 'PA', 'Panama', 'Panamá');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(174, 'PE', 'Peru', 'Perú');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(175, 'PF', 'French Polynesia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(176, 'PG', 'Papua New Guinea', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(177, 'PH', 'Philippines', 'Philippines');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(178, 'PK', 'Pakistan', 'پاکستان');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(179, 'PL', 'Poland', 'Polska');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(180, 'PM', 'St. Pierre and Miquelon', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(181, 'PN', 'Pitcairn', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(182, 'PR', 'Puerto Rico', 'Puerto Rico');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(183, 'PS', 'Palestinian Territory', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(184, 'PT', 'Portugal', 'Portugal');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(185, 'PW', 'Palau', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(186, 'PY', 'Paraguay', 'Paraguay');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(187, 'QA', 'Qatar', 'قطر');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(188, 'RE', 'Reunion', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(189, 'RO', 'Romania', 'România');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(190, 'RS', 'Serbia', 'Srbija');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(191, 'RU', 'Russia', 'Россия');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(192, 'RW', 'Rwanda', 'Rwanda');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(193, 'SA', 'Saudi Arabia', 'المملكة العربية السعودية');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(194, 'SB', 'Solomon Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(195, 'SC', 'Seychelles', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(196, 'SD', 'Sudan', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(197, 'SE', 'Sweden', 'Sverige');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(198, 'SG', 'Singapore', '新加坡');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(199, 'SH', 'Saint Helena', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(200, 'SI', 'Slovenia', 'Slovenija');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(201, 'SJ', 'Svalbard and Jan Mayen Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(202, 'SK', 'Slovakia', 'Slovenská republika');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(203, 'SL', 'Sierra Leone', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(204, 'SM', 'San Marino', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(205, 'SN', 'Senegal', 'Senegaal');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(206, 'SO', 'Somalia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(207, 'SR', 'Suriname', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(208, 'SS', 'South Sudan', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(209, 'ST', 'Sao Tome and Principe', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(210, 'SV', 'El Salvador', 'El Salvador');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(211, 'SX', 'Saint-Martin (Pays-Bas)', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(212, 'SY', 'Syria', 'سوريا');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(213, 'SZ', 'Swaziland', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(214, 'TC', 'Turks and Caicos Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(215, 'TD', 'Chad', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(216, 'TF', 'French Southern Territories', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(217, 'TG', 'Togo', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(218, 'TH', 'Thailand', 'ไทย');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(219, 'TJ', 'Tajikistan', 'Тоҷикистон');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(220, 'TK', 'Tokelau', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(221, 'TL', 'Timor-Leste', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(222, 'TM', 'Turkmenistan', 'Türkmenistan');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(223, 'TN', 'Tunisia', 'تونس');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(224, 'TO', 'Tonga', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(225, 'TR', 'Turkey', 'Türkiye');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(226, 'TT', 'Trinidad and Tobago', 'Trinidad and Tobago');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(227, 'TV', 'Tuvalu', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(228, 'TW', 'Taiwan', '台灣');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(229, 'TZ', 'Tanzania', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(230, 'UA', 'Ukraine', 'Україна');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(231, 'UG', 'Uganda', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(232, 'UM', 'United States Minor Outlying Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(233, 'US', 'United States', 'United States');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(234, 'UY', 'Uruguay', 'Uruguay');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(235, 'UZ', 'Uzbekistan', 'Ўзбекистон Республикаси');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(236, 'VA', 'Vatican', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(237, 'VC', 'Saint Vincent and the Grenadines', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(238, 'VE', 'Bolivarian Republic of Venezuela', 'Republica Bolivariana de Venezuela');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(239, 'VG', 'Virgin Islands (British)', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(240, 'VI', 'Virgin Islands (U.S.)', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(241, 'VN', 'Vietnam', 'Việt Nam');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(242, 'VU', 'Vanuatu', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(243, 'WF', 'Wallis and Futuna Islands', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(244, 'WS', 'Samoa', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(245, 'YE', 'Yemen', 'اليمن');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(246, 'YT', 'Mayotte', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(247, 'ZA', 'South Africa', 'Suid-Afrika');
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(248, 'ZM', 'Zambia', null);
INSERT INTO "Country"("CountryId", "Code", "Name", "NativeName") VALUES(249, 'ZW', 'Zimbabwe', 'Zimbabwe');